Framework=Playwright Automation Framework
Framework Version=v1.2.0
Environment=uat
Browser=Chromium
Execution=Parallel
Node Version=v24.18.0
Operating System=Darwin 25.5.0
Base URL=https://demo.playwright.dev/todomvc/
Execution Date=8/19/2026, 5:14:31 PM
