Framework=Playwright Automation Framework
Framework Version=v1.2.0
Environment=UAT
Browser=Chromium
Execution=Parallel
Node Version=v24.18.0
Operating System=Darwin 25.5.0
Base URL=https://playwright.dev/
Execution Date=8/8/2026, 11:03:27 AM
