Framework=Playwright Automation Framework
Framework Version=v1.2.0
Environment=uat
Browser=Chromium
Execution=Parallel
Node Version=v24.18.0
Operating System=Darwin 25.6.0
Base URL=https://www.testerrank.com/practice
Execution Date=9/17/2026, 7:07:01 PM
